name: DevSecOps Secure Pipeline

on:
  push:
    branches: [ main, candidate-assessment ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    name: "Security Scan: Code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit, Gitleaks, Trivy
        run: |
          pip install bandit

          # Install Trivy (modern method)
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y trivy

          # Install Gitleaks
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | sh -s -- -b /usr/local/bin v8.18.0

      - name: Run Multi-Scanner Orchestrator
        run: |
          python ./scripts/multi-scanner-orchestrator/security-scan.py --path . --format text

  iac-scan:
    name: "Security Scan: IaC"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy for IaC
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Terraform files
        run: trivy config ./infrastructure/terraform/

  container-scan:
    name: "Security Scan: Container"
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build application image
        run: docker build -t devsecops-app:latest ./application

      - name: Scan container image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          scan-ref: 'devsecops-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

  deploy-preview:
    name: "Deploy Preview"
    runs-on: ubuntu-latest
    needs: [security-scan, iac-scan, container-scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init & Plan
        run: |
          cd infrastructure/terraform
          terraform init
          terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Success
        run: echo "✅ All security checks passed! Deployment can proceed."
